"""Your migration message

Revision ID: 775b08e35dcc
Revises: b260be8d1865
Create Date: 2023-10-05 10:41:20.539979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '775b08e35dcc'
down_revision = 'b260be8d1865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labours')
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.alter_column('acreage',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.alter_column('acreage',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=False)

    op.create_table('labours',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('labour_allocation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('work_schedule', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name='labours_farm_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='labours_pkey')
    )
    # ### end Alembic commands ###
