"""Your_migration_message

Revision ID: 8ab87fc5ac28
Revises: eb5081a3fa0d
Create Date: 2023-11-29 01:58:53.308140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab87fc5ac28'
down_revision = 'eb5081a3fa0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('information', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestocks', schema=None) as batch_op:
        batch_op.drop_column('information')

    # ### end Alembic commands ###
