"""Initial_migration

Revision ID: eb5081a3fa0d
Revises: ab089021f093
Create Date: 2023-11-29 00:45:53.590974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5081a3fa0d'
down_revision = 'ab089021f093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestocks', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
