"""Your_migration_message

Revision ID: f88113172219
Revises: 8ab87fc5ac28
Create Date: 2023-11-29 02:11:01.901537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88113172219'
down_revision = '8ab87fc5ac28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('information', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestocks', schema=None) as batch_op:
        batch_op.drop_column('information')

    # ### end Alembic commands ###
